version: '3.8'

services:
  server:
    build: ./server
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app
      - /app/node_modules
      - /app/.pnpm-store
    environment:
      - NODE_ENV=production
      - PNPM_HOME=/app/node_modules/.pnpm
    depends_on:
      - db

  client:
    build: ./client
    ports:
      - "3000:80"
    depends_on:
      - server

  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: team_3205
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
